version: '3'

networks:
  front:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_FRONT}
  back:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_BACK}

services:
  nginx:
    build:
      context: ./nginx
    image: ${COMPOSE_PROJECT_NAME}_nginx:latest
    volumes:
      - ../public:/var/www/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      front:
        ipv4_address: ${NGINX_IP_FRONT}
      back:
        ipv4_address: ${NGINX_IP_BACK}
    ports:
      - "80:80"
      - "443:443"

  php-fpm:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
    image: ${COMPOSE_PROJECT_NAME}_php-fpm:latest
    volumes:
      - ../src:/var/www/src
      - ../public:/var/www/public
      - ../routes:/var/www/routes
      - ../templates:/var/www/templates
      - ../vendor:/var/www/vendor
      - ../.env:/var/www/.env
    networks:
      back:
        ipv4_address: ${PHP_IP_BACK}

  mariadb:
    build:
      context: ./mariadb
    image: ${COMPOSE_PROJECT_NAME}_mariadb:latest
    restart: always
    environment:
      - MYSQL_DATABASE=${MARIA_DATABASE}
      - MYSQL_USER=${MARIA_USER}
      - MYSQL_PASSWORD=${MARIA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIA_ROOT_PASSWORD}
    networks:
      back:
        ipv4_address: ${MARIADB_IP_BACK}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - ./mariadb/init.d:/docker-entrypoint-init.d